### ISSUE TITLE
How to Update Gradle Spring Boot Dependencies

### ISSUE THREAD

**Issue by JoeBanjo5050** [morzel85/blog-post-spring-arduino#1]
I am struggling to get this project to run after many hours of updating several aspects of the build.gradle file to include gradle version, spring-boot RELEASE, and altering many of the dependencies, as well as ensuring that the gradle-wrapper.properties were updates as well.

I am on a Windows 10 x64 and have the latest JDK installed. I have managed to get VSC to move the error past line 16: and line 43: (this wrapper syntax is deprecated)of build.graddle, but then the methods are overrun with errors.

I would at least be happy if at minimum I knew that this project is too old to be wroth the time reviving, and better to start new, but I am not sure that I have the skills to execute a fresh build on my timeline.

If someone experienced could please provide a vector, I would greatly appreciate it, as this is a really cool project.

**Comment by morzel85** [comment]
I haven't looked at this project for 6 years :) but it would be probably easier to start a new Spring Boot app and just cherry-pick the code related to turret control and connection to Arduino (the code described in [the post](https://en.morzel.net/post/OoB-Controlling-gun-turret-with-Spring-Boot-REST-service-(JavaArduino)))...

**Comment by JoeBanjo5050** [comment]
Solid advice. I re-built the project and at least have Spring Boot running now with no debug issues in VSC.; however, I am still seeing 'Failed to start bean '_webServerStartStop'; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat serve_r' after context initialization. I am wondering if it is due to the  @PreDestroy disconnect method serial !=null on line 44 of ArduinoConnection.java?


 .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.4.4)

2021-03-30 21:03:32.673  INFO 19492 --- [           main] c.s.SpringArduinoApplication             : Starting SpringArduinoApplication using Java 11.0.10 on DESKTOP-009DOII with PID 19492 (C:\Users\leebr\Desktop\springarduino\bin\main started by leebr in C:\Users\leebr\Desktop\springarduino)
2021-03-30 21:03:32.676  INFO 19492 --- [           main] c.s.SpringArduinoApplication             : No active profile set, falling back to default profiles: default
2021-03-30 21:03:33.511  INFO 19492 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8090 (http)
2021-03-30 21:03:33.522  INFO 19492 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-03-30 21:03:33.523  INFO 19492 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.44]
2021-03-30 21:03:33.588  INFO 19492 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-03-30 21:03:33.589  INFO 19492 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 868 ms
2021-03-30 21:03:33.638  INFO 19492 --- [           main] com.springarduino.ArduinoConnection      : ArduinoConnection PostConstruct callback: connecting to Arduino...
2021-03-30 21:03:33.642  INFO 19492 --- [           main] gnu.io.CommPortIdentifier                : CommPortIdentifier:static initialization(), OS: Windows 10, arch: amd64
2021-03-30 21:03:33.643  INFO 19492 --- [           main] gnu.io.CommPortIdentifier                : Load the driver.
2021-03-30 21:03:33.645  INFO 19492 --- [           main] gnu.io.RXTXCommDriver                    : RXTXCommDriver : static initializer.
2021-03-30 21:03:33.646  INFO 19492 --- [           main] gnu.io.SerialManager                     : Load native library.
2021-03-30 21:03:33.647  INFO 19492 --- [           main] gnu.io.NativeResource                    : Load lib: NRJavaSerial
2021-03-30 21:03:33.648  INFO 19492 --- [           main] gnu.io.NativeResource                    : Loading from file: /native/windows/x86_64/libNRJavaSerial.dll
2021-03-30 21:03:33.650  INFO 19492 --- [           main] gnu.io.NativeResource                    : Copy resources to: C:\Users\leebr\AppData\Local\Temp\libNRJavaSerial_leebr_0\libNRJavaSerial.dll
2021-03-30 21:03:33.656  INFO 19492 --- [           main] gnu.io.NativeResource                    : Load resource from absolute path: C:\Users\leebr\AppData\Local\Temp\libNRJavaSerial_leebr_0\libNRJavaSerial.dll 
2021-03-30 21:03:33.658  INFO 19492 --- [           main] gnu.io.CommPortIdentifier                : static CommPortIdentifier:getPortIdentifiers()
2021-03-30 21:03:33.659  INFO 19492 --- [           main] gnu.io.RXTXCommDriver                    : RXTXCommDriver:initialize(), osName: Windows 10
2021-03-30 21:03:33.660  INFO 19492 --- [           main] gnu.io.RXTXCommDriver                    : scanning device directory //./ for ports of type 1
2021-03-30 21:03:38.861  INFO 19492 --- [           main] gnu.io.RXTXCommDriver                    : RXTXCommDriver:initialize(), osName: Windows 10
2021-03-30 21:03:38.861  INFO 19492 --- [           main] gnu.io.RXTXCommDriver                    : scanning device directory //./ for ports of type 1
2021-03-30 21:03:44.045  INFO 19492 --- [           main] gnu.io.CommPortIdentifier                : Have not implemented native_psmisc_report_owner(PortName)); in CommPortIdentifier
2021-03-30 21:03:44.045  INFO 19492 --- [           main] gnu.io.RXTXCommDriver                    : RXTXCommDriver:getCommPort(COM6,1)
2021-03-30 21:03:44.061  INFO 19492 --- [           main] com.springarduino.ArduinoConnection      : Arduino connection opened!
2021-03-30 21:03:44.161  INFO 19492 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2021-03-30 21:03:44.303  WARN 19492 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
2021-03-30 21:03:44.304  INFO 19492 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2021-03-30 21:03:44.304  INFO 19492 --- [           main] com.springarduino.ArduinoConnection      : ArduinoConnection PreDestroy callback: disconnecting from Arduino...
2021-03-30 21:03:44.339  INFO 19492 --- [           main] com.springarduino.ArduinoConnection      : Arduino connection closed!
2021-03-30 21:03:44.342  INFO 19492 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2021-03-30 21:03:44.354  INFO 19492 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-03-30 21:03:44.370 ERROR 19492 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181) ~[spring-context-5.3.5.jar:5.3.5]
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.5.jar:5.3.5]
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.3.5.jar:5.3.5]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[spring-context-5.3.5.jar:5.3.5]
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) ~[spring-context-5.3.5.jar:5.3.5]
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935) ~[spring-context-5.3.5.jar:5.3.5]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.5.jar:5.3.5]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.4.jar:2.4.4]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:769) ~[spring-boot-2.4.4.jar:2.4.4]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) ~[spring-boot-2.4.4.jar:2.4.4]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[spring-boot-2.4.4.jar:2.4.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[spring-boot-2.4.4.jar:2.4.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1313) ~[spring-boot-2.4.4.jar:2.4.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[spring-boot-2.4.4.jar:2.4.4]
        at com.springarduino.SpringArduinoApplication.main(SpringArduinoApplication.java:10) ~[main/:na]
Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:229) ~[spring-boot-2.4.4.jar:2.4.4]
        at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:43) ~[spring-boot-2.4.4.jar:2.4.4]
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-5.3.5.jar:5.3.5]
        ... 15 common frames omitted
Caused by: java.lang.IllegalArgumentException: standardService.connector.startFailed
        at org.apache.catalina.core.StandardService.addConnector(StandardService.java:244) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:282) ~[spring-boot-2.4.4.jar:2.4.4]
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:213) ~[spring-boot-2.4.4.jar:2.4.4]
        ... 17 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Protocol handler start failed
        at org.apache.catalina.connector.Connector.startInternal(Connector.java:1075) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.core.StandardService.addConnector(StandardService.java:240) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        ... 19 common frames omitted
Caused by: java.net.BindException: Cannot assign requested address: bind
        at java.base/sun.nio.ch.Net.bind0(Native Method) ~[na:na]
        at java.base/sun.nio.ch.Net.bind(Net.java:455) ~[na:na]
        at java.base/sun.nio.ch.Net.bind(Net.java:447) ~[na:na]
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227) ~[na:na]
        at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:300) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:253) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1204) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1290) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:614) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.connector.Connector.startInternal(Connector.java:1072) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        ... 21 common frames omitted

PS C:\Users\leebr\Desktop\springarduino>

**Comment by JoeBanjo5050** [comment]
I figured it out. Nothing more than needing to change server.address = 192.168.0.17 to 192.168.0.21 and now it runs perfectly after the Spring Boot refresh.

I sent a pull request prior to the change, but everything else was the same and I learned a ton about Spring Boot, Tomcat, Beans, and Gradle in the process.
